import { AbpHttpInterceptor, RefreshTokenService } from '@abp/abpHttpInterceptor';
import { HTTP_INTERCEPTORS } from '@angular/common/http';
import { NgModule } from '@angular/core';
import * as ApiServiceProxies from './service-proxies';
import { ZeroRefreshTokenService } from '@account/auth/zero-refresh-token.service';

@NgModule({
    providers: [
        ApiServiceProxies.EquipTimetablesServiceProxy,        
        ApiServiceProxies.TimetablesServiceProxy,        
        ApiServiceProxies.CostTypeseServiceProxy,        
        ApiServiceProxies.AccountsServiceProxy,               
        ApiServiceProxies.UnionPayRatesServiceProxy,        
        ApiServiceProxies.PayperiodHistoriesServiceProxy,        
        ApiServiceProxies.StatusUpdatesServiceProxy,        
        ApiServiceProxies.ShiftExpensesServiceProxy,        
        ApiServiceProxies.EmployeeUnionsServiceProxy,        
        ApiServiceProxies.JobUnionsServiceProxy,        
        ApiServiceProxies.UnionsServiceProxy,        
        ApiServiceProxies.ShiftResourcesServiceProxy,        
        ApiServiceProxies.JobCategoriesServiceProxy,        
        ApiServiceProxies.JobPhaseCodesServiceProxy,        
        ApiServiceProxies.ShiftsServiceProxy,        
        ApiServiceProxies.PayPeriodsServiceProxy,        
        ApiServiceProxies.TimesheetsServiceProxy,        
        ApiServiceProxies.StatusesServiceProxy,        
        ApiServiceProxies.ExpenseTypesesServiceProxy,        
        ApiServiceProxies.PayTypesesServiceProxy,        
        ApiServiceProxies.ResourceReservationsesServiceProxy,        
        ApiServiceProxies.JobsesServiceProxy,        
        ApiServiceProxies.JobClassesesServiceProxy,        
        ApiServiceProxies.AddressesesServiceProxy,        
        ApiServiceProxies.ResourceEquipmentInfosesServiceProxy,        
        ApiServiceProxies.ResourceWorkerInfosesServiceProxy,        
        ApiServiceProxies.WorkerClaseesesServiceProxy,        
        ApiServiceProxies.ResourcesesServiceProxy,        
        ApiServiceProxies.ECCOSTSServiceProxy,        
        ApiServiceProxies.EQUIPMENTSServiceProxy,        
        ApiServiceProxies.PRDEDRATESServiceProxy,        
        ApiServiceProxies.JCJOBsServiceProxy,        
        ApiServiceProxies.PRCLASSsServiceProxy,        
        ApiServiceProxies.JCUNIONsServiceProxy,        
        ApiServiceProxies.JACCATsServiceProxy,        
        ApiServiceProxies.PREMPLOYEESServiceProxy,        
        ApiServiceProxies.AuditLogServiceProxy,
        ApiServiceProxies.CachingServiceProxy,
        ApiServiceProxies.ChatServiceProxy,
        ApiServiceProxies.CommonLookupServiceProxy,
        ApiServiceProxies.EditionServiceProxy,
        ApiServiceProxies.FriendshipServiceProxy,
        ApiServiceProxies.HostSettingsServiceProxy,
        ApiServiceProxies.InstallServiceProxy,
        ApiServiceProxies.LanguageServiceProxy,
        ApiServiceProxies.NotificationServiceProxy,
        ApiServiceProxies.OrganizationUnitServiceProxy,
        ApiServiceProxies.PermissionServiceProxy,
        ApiServiceProxies.ProfileServiceProxy,
        ApiServiceProxies.RoleServiceProxy,
        ApiServiceProxies.SessionServiceProxy,
        ApiServiceProxies.TenantServiceProxy,
        ApiServiceProxies.TenantDashboardServiceProxy,
        ApiServiceProxies.TenantSettingsServiceProxy,
        ApiServiceProxies.TimingServiceProxy,
        ApiServiceProxies.UserServiceProxy,
        ApiServiceProxies.UserLinkServiceProxy,
        ApiServiceProxies.UserLoginServiceProxy,
        ApiServiceProxies.WebLogServiceProxy,
        ApiServiceProxies.AccountServiceProxy,
        ApiServiceProxies.TokenAuthServiceProxy,
        ApiServiceProxies.TenantRegistrationServiceProxy,
        ApiServiceProxies.HostDashboardServiceProxy,
        ApiServiceProxies.PaymentServiceProxy,
        ApiServiceProxies.DemoUiComponentsServiceProxy,
        ApiServiceProxies.InvoiceServiceProxy,
        ApiServiceProxies.SubscriptionServiceProxy,
        ApiServiceProxies.InstallServiceProxy,
        ApiServiceProxies.UiCustomizationSettingsServiceProxy,
        ApiServiceProxies.PayPalPaymentServiceProxy,
        ApiServiceProxies.StripePaymentServiceProxy,
        ApiServiceProxies.DashboardCustomizationServiceProxy,
        { provide: RefreshTokenService, useClass: ZeroRefreshTokenService },
        { provide: HTTP_INTERCEPTORS, useClass: AbpHttpInterceptor, multi: true }
    ]
})
export class ServiceProxyModule { }
